package main

import (
	"context"
	"fmt"
	"html"
	"log"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// serveWorldHTML serves the SPA index for /world, but rewrites the og/twitter
// meta block so social crawlers (which don't run JS) get a per-link preview
// of the photo region the deep link points at. The dynamic image itself is
// generated by getOgPreview (og_preview.go).
//
// Injection is a string-replace between sentinel comments embedded in
// index.html (<!-- OG:BEGIN --> ... <!-- OG:END -->). The block survives Vite
// verbatim, and the replace never touches the hashed <script> tag.

const (
	ogSentinelBegin = "<!-- OG:BEGIN -->"
	ogSentinelEnd   = "<!-- OG:END -->"
)

var (
	worldTemplateOnce sync.Once
	worldTemplate     string // index.html bytes, loaded once
	worldTemplateErr  error
	ogSentinelWarn    sync.Once
)

func (s *Server) loadWorldTemplate() (string, error) {
	worldTemplateOnce.Do(func() {
		b, err := os.ReadFile(filepath.Join(s.staticDir, "index.html"))
		if err != nil {
			worldTemplateErr = err
			return
		}
		worldTemplate = string(b)
	})
	return worldTemplate, worldTemplateErr
}

func (s *Server) serveWorldHTML(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Cache-Control", "no-cache")
	tmpl, err := s.loadWorldTemplate()
	if err != nil {
		// Fall back to the static file rather than 500 the page.
		http.ServeFile(w, r, filepath.Join(s.staticDir, "index.html"))
		return
	}

	begin := strings.Index(tmpl, ogSentinelBegin)
	end := strings.Index(tmpl, ogSentinelEnd)
	if begin < 0 || end < 0 || end < begin {
		ogSentinelWarn.Do(func() {
			log.Printf("og: sentinels %q/%q not found in index.html; serving default card", ogSentinelBegin, ogSentinelEnd)
		})
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(tmpl))
		return
	}

	block := s.ogTagsForWorld(r)
	out := tmpl[:begin] + block + tmpl[end+len(ogSentinelEnd):]
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write([]byte(out))
}

const ogDescription = "Align historical photographs to a 3D model of the world and composite them into 360° panoramas."

// ogTagsForWorld renders the meta block. When the deep link carries a valid
// sta it emits a dynamic summary_large_image card pointing at /og/preview.jpg;
// otherwise it returns the static default card.
func (s *Server) ogTagsForWorld(r *http.Request) string {
	q := r.URL.Query()
	sta := q.Get("sta")
	if !validID(sta) {
		return defaultOgBlock()
	}

	base := s.baseURL(r)
	pageURL := base + r.URL.RequestURI()

	// The card endpoint takes the same view params as the page.
	cardQ := url.Values{}
	cardQ.Set("sta", sta)
	for _, k := range []string{"az", "alt", "fov"} {
		if v := q.Get(k); v != "" {
			cardQ.Set(k, v)
		}
	}
	imageURL := base + "/og/preview.jpg?" + cardQ.Encode()

	title := "Viewfinder"
	if name := s.stationName(r.Context(), sta); name != "" {
		title = name + " — Viewfinder"
	}

	var b strings.Builder
	meta := func(prop, attr, content string) {
		fmt.Fprintf(&b, "  <meta %s=%q content=%q>\n", attr, prop, html.EscapeString(content))
	}
	b.WriteString(ogSentinelBegin + "\n")
	meta("og:site_name", "property", "Viewfinder")
	meta("og:type", "property", "website")
	meta("og:title", "property", title)
	meta("og:description", "property", ogDescription)
	meta("og:url", "property", pageURL)
	meta("og:image", "property", imageURL)
	meta("og:image:width", "property", "1200")
	meta("og:image:height", "property", "630")
	meta("twitter:card", "name", "summary_large_image")
	meta("twitter:title", "name", title)
	meta("twitter:description", "name", ogDescription)
	meta("twitter:image", "name", imageURL)
	b.WriteString("  " + ogSentinelEnd)
	return b.String()
}

func defaultOgBlock() string {
	var b strings.Builder
	b.WriteString(ogSentinelBegin + "\n")
	b.WriteString(`  <meta property="og:site_name" content="Viewfinder">` + "\n")
	b.WriteString(`  <meta property="og:type" content="website">` + "\n")
	b.WriteString(`  <meta property="og:title" content="Viewfinder">` + "\n")
	fmt.Fprintf(&b, "  <meta property=\"og:description\" content=%q>\n", ogDescription)
	b.WriteString(`  <meta property="og:image" content="/assets/apple-touch-icon.png">` + "\n")
	b.WriteString(`  <meta name="twitter:card" content="summary">` + "\n")
	b.WriteString(`  <meta name="twitter:title" content="Viewfinder">` + "\n")
	fmt.Fprintf(&b, "  <meta name=\"twitter:description\" content=%q>\n", ogDescription)
	b.WriteString(`  <meta name="twitter:image" content="/assets/apple-touch-icon.png">` + "\n")
	b.WriteString("  " + ogSentinelEnd)
	return b.String()
}

func (s *Server) stationName(ctx context.Context, id string) string {
	st, err := scanStation(s.db.QueryRow(ctx,
		`SELECT `+stationCols+` FROM stations WHERE id = $1`, id))
	if err != nil || st.Name == nil {
		return ""
	}
	return strings.TrimSpace(*st.Name)
}

// baseURL is the absolute origin for og:image / og:url. PUBLIC_BASE_URL wins;
// otherwise derive from the request (X-Forwarded-Proto + Host), defaulting to
// https except for bare localhost.
func (s *Server) baseURL(r *http.Request) string {
	if s.publicBaseURL != "" {
		return s.publicBaseURL
	}
	scheme := r.Header.Get("X-Forwarded-Proto")
	if scheme == "" {
		scheme = "https"
		if host := r.Host; strings.HasPrefix(host, "localhost") || strings.HasPrefix(host, "127.0.0.1") {
			scheme = "http"
		}
	}
	return scheme + "://" + r.Host
}
