// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package main

import (
	"time"
)

// Defines values for CPConstraintType.
const (
	Level CPConstraintType = "level"
	Plumb CPConstraintType = "plumb"
)

// Valid indicates whether the value is a known member of the CPConstraintType enum.
func (e CPConstraintType) Valid() bool {
	switch e {
	case Level:
		return true
	case Plumb:
		return true
	default:
		return false
	}
}

// Defines values for CommitKind.
const (
	Merge  CommitKind = "merge"
	Revert CommitKind = "revert"
)

// Valid indicates whether the value is a known member of the CommitKind enum.
func (e CommitKind) Valid() bool {
	switch e {
	case Merge:
		return true
	case Revert:
		return true
	default:
		return false
	}
}

// Defines values for CreateSessionResponseStatus.
const (
	CreateSessionResponseStatusAbandoned CreateSessionResponseStatus = "abandoned"
	CreateSessionResponseStatusMerged    CreateSessionResponseStatus = "merged"
	CreateSessionResponseStatusOpen      CreateSessionResponseStatus = "open"
)

// Valid indicates whether the value is a known member of the CreateSessionResponseStatus enum.
func (e CreateSessionResponseStatus) Valid() bool {
	switch e {
	case CreateSessionResponseStatusAbandoned:
		return true
	case CreateSessionResponseStatusMerged:
		return true
	case CreateSessionResponseStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for EntityChangeKind.
const (
	EntityChangeKindControlPoint EntityChangeKind = "control_point"
	EntityChangeKindPhoto        EntityChangeKind = "photo"
	EntityChangeKindStation      EntityChangeKind = "station"
)

// Valid indicates whether the value is a known member of the EntityChangeKind enum.
func (e EntityChangeKind) Valid() bool {
	switch e {
	case EntityChangeKindControlPoint:
		return true
	case EntityChangeKindPhoto:
		return true
	case EntityChangeKindStation:
		return true
	default:
		return false
	}
}

// Defines values for EntityRefEntityType.
const (
	EntityRefEntityTypeControlPoint     EntityRefEntityType = "control_point"
	EntityRefEntityTypeCpConstraint     EntityRefEntityType = "cp_constraint"
	EntityRefEntityTypeCpSurface        EntityRefEntityType = "cp_surface"
	EntityRefEntityTypeImageMeasurement EntityRefEntityType = "image_measurement"
	EntityRefEntityTypePhoto            EntityRefEntityType = "photo"
	EntityRefEntityTypeStation          EntityRefEntityType = "station"
)

// Valid indicates whether the value is a known member of the EntityRefEntityType enum.
func (e EntityRefEntityType) Valid() bool {
	switch e {
	case EntityRefEntityTypeControlPoint:
		return true
	case EntityRefEntityTypeCpConstraint:
		return true
	case EntityRefEntityTypeCpSurface:
		return true
	case EntityRefEntityTypeImageMeasurement:
		return true
	case EntityRefEntityTypePhoto:
		return true
	case EntityRefEntityTypeStation:
		return true
	default:
		return false
	}
}

// Defines values for SessionOpEntityType.
const (
	SessionOpEntityTypeControlPoint     SessionOpEntityType = "control_point"
	SessionOpEntityTypeCpConstraint     SessionOpEntityType = "cp_constraint"
	SessionOpEntityTypeCpSurface        SessionOpEntityType = "cp_surface"
	SessionOpEntityTypeImageMeasurement SessionOpEntityType = "image_measurement"
	SessionOpEntityTypePhoto            SessionOpEntityType = "photo"
	SessionOpEntityTypeStation          SessionOpEntityType = "station"
)

// Valid indicates whether the value is a known member of the SessionOpEntityType enum.
func (e SessionOpEntityType) Valid() bool {
	switch e {
	case SessionOpEntityTypeControlPoint:
		return true
	case SessionOpEntityTypeCpConstraint:
		return true
	case SessionOpEntityTypeCpSurface:
		return true
	case SessionOpEntityTypeImageMeasurement:
		return true
	case SessionOpEntityTypePhoto:
		return true
	case SessionOpEntityTypeStation:
		return true
	default:
		return false
	}
}

// Defines values for SessionOpOp.
const (
	Delete SessionOpOp = "delete"
	Insert SessionOpOp = "insert"
	Update SessionOpOp = "update"
)

// Valid indicates whether the value is a known member of the SessionOpOp enum.
func (e SessionOpOp) Valid() bool {
	switch e {
	case Delete:
		return true
	case Insert:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for SessionStateStatus.
const (
	SessionStateStatusAbandoned SessionStateStatus = "abandoned"
	SessionStateStatusMerged    SessionStateStatus = "merged"
	SessionStateStatusOpen      SessionStateStatus = "open"
)

// Valid indicates whether the value is a known member of the SessionStateStatus enum.
func (e SessionStateStatus) Valid() bool {
	switch e {
	case SessionStateStatusAbandoned:
		return true
	case SessionStateStatusMerged:
		return true
	case SessionStateStatusOpen:
		return true
	default:
		return false
	}
}

// CPConstraint defines model for CPConstraint.
type CPConstraint struct {
	// ConstraintType plumb: cp_a and cp_b share est_lat and est_lng (vertical line);
	// level: cp_a and cp_b share est_alt (horizontal alignment).
	ConstraintType CPConstraintType `json:"constraint_type"`

	// CpAId 13-character base32 server-assigned id
	CpAId ID `json:"cp_a_id"`

	// CpBId 13-character base32 server-assigned id
	CpBId     ID        `json:"cp_b_id"`
	CreatedAt time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID        ID        `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CPConstraintCreate POST body for `/control-point-constraints`. The handler
// swaps `cp_a_id` and `cp_b_id` if needed to satisfy the
// canonical `cp_a_id < cp_b_id` ordering before insert.
type CPConstraintCreate struct {
	// ConstraintType plumb: cp_a and cp_b share est_lat and est_lng (vertical line);
	// level: cp_a and cp_b share est_alt (horizontal alignment).
	ConstraintType CPConstraintType `json:"constraint_type"`

	// CpAId 13-character base32 server-assigned id
	CpAId ID `json:"cp_a_id"`

	// CpBId 13-character base32 server-assigned id
	CpBId ID `json:"cp_b_id"`
}

// CPConstraintPatch Partial-update body. Only `constraint_type` is mutable.
type CPConstraintPatch struct {
	// ConstraintType plumb: cp_a and cp_b share est_lat and est_lng (vertical line);
	// level: cp_a and cp_b share est_alt (horizontal alignment).
	ConstraintType *CPConstraintType `json:"constraint_type,omitempty"`
}

// CPConstraintType plumb: cp_a and cp_b share est_lat and est_lng (vertical line);
// level: cp_a and cp_b share est_alt (horizontal alignment).
type CPConstraintType string

// CPSurface Polygonal surface anchored on 3 (triangle, cp_4_id null) or 4 (quad)
// control points. Surfaces are visualization-only; the solver doesn't
// read them.
type CPSurface struct {
	// Cp1ID 13-character base32 server-assigned id
	Cp1ID ID `json:"cp_1_id"`

	// Cp2ID 13-character base32 server-assigned id
	Cp2ID ID `json:"cp_2_id"`

	// Cp3ID 13-character base32 server-assigned id
	Cp3ID     ID        `json:"cp_3_id"`
	Cp4ID     *ID       `json:"cp_4_id,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID        ID        `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// CPSurfaceCreate POST body for `/control-point-surfaces`. cp_4_id null or omitted
// makes a triangle; otherwise a quad. All non-null ids must be
// pairwise distinct.
type CPSurfaceCreate struct {
	// Cp1ID 13-character base32 server-assigned id
	Cp1ID ID `json:"cp_1_id"`

	// Cp2ID 13-character base32 server-assigned id
	Cp2ID ID `json:"cp_2_id"`

	// Cp3ID 13-character base32 server-assigned id
	Cp3ID ID  `json:"cp_3_id"`
	Cp4ID *ID `json:"cp_4_id,omitempty"`
}

// Commit defines model for Commit.
type Commit struct {
	CreatedAt time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID              ID         `json:"id"`
	Kind            CommitKind `json:"kind"`
	Message         *string    `json:"message,omitempty"`
	ParentSeq       *int64     `json:"parent_seq,omitempty"`
	RevertsCommitID *ID        `json:"reverts_commit_id,omitempty"`
	Seq             int64      `json:"seq"`
	SourceSessionID *ID        `json:"source_session_id,omitempty"`
}

// CommitKind defines model for Commit.Kind.
type CommitKind string

// CommitMessage defines model for CommitMessage.
type CommitMessage struct {
	Message *string `json:"message,omitempty"`
}

// CommitRef defines model for CommitRef.
type CommitRef struct {
	// CommitID 13-character base32 server-assigned id
	CommitID ID    `json:"commit_id"`
	Seq      int64 `json:"seq"`
}

// CommitWithOps defines model for CommitWithOps.
type CommitWithOps struct {
	Commit Commit      `json:"commit"`
	Ops    []SessionOp `json:"ops"`
}

// ConflictsResponse defines model for ConflictsResponse.
type ConflictsResponse struct {
	Conflicts []EntityRef `json:"conflicts"`
	Error     string      `json:"error"`
}

// ControlPoint A real-world landmark with a user-seeded location estimate
// (est_lat / est_lng / est_alt) and image-measurement observations
// across photos and stations. The estimate is set when the CP is
// created and refined by the location solver as observations accumulate.
type ControlPoint struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`

	// EndedAt when the landmark ceased to exist
	EndedAt *time.Time `json:"ended_at"`

	// EndedBefore when true
	EndedBefore bool `json:"ended_before"`

	// EstAlt meters above sea level; null when the elevation isn't known
	EstAlt *float64 `json:"est_alt"`
	EstLat *float64 `json:"est_lat"`
	EstLng *float64 `json:"est_lng"`

	// ID 13-character base32 server-assigned id
	ID         ID   `json:"id"`
	LockEstAlt bool `json:"lock_est_alt"`
	LockEstLat bool `json:"lock_est_lat"`
	LockEstLng bool `json:"lock_est_lng"`

	// Notes free-form prose describing the control point in detail
	Notes string `json:"notes"`

	// StartedAfter when true
	StartedAfter bool `json:"started_after"`

	// StartedAt when the landmark began existing
	StartedAt *time.Time `json:"started_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// ControlPointFit Goodness-of-fit summary for one CP. fit_rms_rad is the RMS angular
// residual (radians) between every observation's image-plane ray and
// the bearing from its station to the CP's stored estimate — same
// residual the solver minimizes. observation_count is the number of
// image measurements that contributed.
type ControlPointFit struct {
	FitRmsRad float64 `json:"fit_rms_rad"`

	// ID 13-character base32 server-assigned id
	ID               ID  `json:"id"`
	ObservationCount int `json:"observation_count"`
}

// ControlPointFits defines model for ControlPointFits.
type ControlPointFits struct {
	ControlPoints []ControlPointFit `json:"control_points"`
}

// ControlPointImageObservation defines model for ControlPointImageObservation.
type ControlPointImageObservation struct {
	Aspect float64 `json:"aspect"`

	// ID 13-character base32 server-assigned id
	ID      ID      `json:"id"`
	PhotoAz float64 `json:"photo_az"`

	// PhotoID 13-character base32 server-assigned id
	PhotoID           ID        `json:"photo_id"`
	PhotoRoll         float64   `json:"photo_roll"`
	PhotoTilt         float64   `json:"photo_tilt"`
	SizeRad           float64   `json:"size_rad"`
	StationCapturedAt time.Time `json:"station_captured_at"`

	// StationID 13-character base32 server-assigned id
	StationID   ID      `json:"station_id"`
	StationLat  float64 `json:"station_lat"`
	StationLng  float64 `json:"station_lng"`
	StationName *string `json:"station_name"`
	U           float64 `json:"u"`
	V           float64 `json:"v"`
}

// ControlPointObservations defines model for ControlPointObservations.
type ControlPointObservations struct {
	ImageMeasurements []ControlPointImageObservation `json:"image_measurements"`
}

// ControlPointPatch Body for both `POST /control-points` and `PUT
// /control-points/{id}`. Every field optional. On POST, omitted
// fields take their column defaults; on PUT, omitted fields are
// preserved.
type ControlPointPatch struct {
	Description  *string    `json:"description,omitempty"`
	EndedAt      *time.Time `json:"ended_at,omitempty"`
	EndedBefore  *bool      `json:"ended_before,omitempty"`
	EstAlt       *float64   `json:"est_alt,omitempty"`
	EstLat       *float64   `json:"est_lat,omitempty"`
	EstLng       *float64   `json:"est_lng,omitempty"`
	LockEstAlt   *bool      `json:"lock_est_alt,omitempty"`
	LockEstLat   *bool      `json:"lock_est_lat,omitempty"`
	LockEstLng   *bool      `json:"lock_est_lng,omitempty"`
	Notes        *string    `json:"notes,omitempty"`
	StartedAfter *bool      `json:"started_after,omitempty"`
	StartedAt    *time.Time `json:"started_at,omitempty"`
}

// ControlPointVisiblePhoto A photo whose horizontal viewshed contains the CP's estimated
// location and whose station capture time overlaps the CP's
// lifespan, but which has no image measurement linking to the CP
// yet. Pose and station coordinates used for the server-side
// viewshed test are intentionally not exposed.
type ControlPointVisiblePhoto struct {
	// PhotoID 13-character base32 server-assigned id
	PhotoID           ID        `json:"photo_id"`
	StationCapturedAt time.Time `json:"station_captured_at"`

	// StationID 13-character base32 server-assigned id
	StationID   ID      `json:"station_id"`
	StationName *string `json:"station_name"`
}

// ControlPointVisiblePhotos defines model for ControlPointVisiblePhotos.
type ControlPointVisiblePhotos struct {
	Photos []ControlPointVisiblePhoto `json:"photos"`
}

// CreateSessionResponse defines model for CreateSessionResponse.
type CreateSessionResponse struct {
	// BaseSeq HEAD seq the session forked from (0 if commit log is empty)
	BaseSeq   int64     `json:"base_seq"`
	CreatedAt time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID ID `json:"id"`

	// NextSeq Next per-session op sequence to be assigned
	NextSeq int64                       `json:"next_seq"`
	Status  CreateSessionResponseStatus `json:"status"`
}

// CreateSessionResponseStatus defines model for CreateSessionResponse.Status.
type CreateSessionResponseStatus string

// CreateStationRequest POST body. lat/lng/captured_at are required; other fields default if omitted.
type CreateStationRequest struct {
	// Alt defaults to 0 when omitted
	Alt        *float64  `json:"alt,omitempty"`
	CapturedAt time.Time `json:"captured_at"`
	Lat        float64   `json:"lat"`
	Lng        float64   `json:"lng"`
	LockAlt    *bool     `json:"lock_alt,omitempty"`

	// LockLat defaults to false when omitted
	LockLat *bool   `json:"lock_lat,omitempty"`
	LockLng *bool   `json:"lock_lng,omitempty"`
	Name    *string `json:"name,omitempty"`
}

// EntityChange One row's before/after for the keys the solver actually moved.
type EntityChange struct {
	After  map[string]float64 `json:"after"`
	Before map[string]float64 `json:"before"`

	// ID 13-character base32 server-assigned id
	ID   ID               `json:"id"`
	Kind EntityChangeKind `json:"kind"`
}

// EntityChangeKind defines model for EntityChange.Kind.
type EntityChangeKind string

// EntityRef One entity touched by a session, optionally annotated with the
// last-commit seq that updated it on main.
type EntityRef struct {
	// EntityID 13-character base32 server-assigned id
	EntityID   ID                  `json:"entity_id"`
	EntityType EntityRefEntityType `json:"entity_type"`
	LastSeq    *int64              `json:"last_seq,omitempty"`
}

// EntityRefEntityType defines model for EntityRef.EntityType.
type EntityRefEntityType string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// HydratedStation defines model for HydratedStation.
type HydratedStation struct {
	// ControlPoints Control points reachable from this station — i.e., those
	// referenced by at least one of this station's measurements.
	// Other CPs (in other stations) are not included.
	ControlPoints     []ControlPoint     `json:"control_points"`
	ImageMeasurements []ImageMeasurement `json:"image_measurements"`
	Photos            []Photo            `json:"photos"`
	Station           Station            `json:"station"`
}

// ID 13-character base32 server-assigned id
type ID = string

// ImageMeasurement Reticle anchor on a photo at (u, v): the user identifies that
// some control point is visible at this image-space position.
type ImageMeasurement struct {
	ControlPointID *ID       `json:"control_point_id"`
	CreatedAt      time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID ID `json:"id"`

	// PhotoID 13-character base32 server-assigned id
	PhotoID   ID        `json:"photo_id"`
	U         float64   `json:"u"`
	UpdatedAt time.Time `json:"updated_at"`
	V         float64   `json:"v"`
}

// ImageMeasurementPatch POST body for `POST /photos/{id}/image-measurements`. u/v
// required; control_point_id optional (null = unlinked).
type ImageMeasurementPatch struct {
	ControlPointID *ID     `json:"control_point_id,omitempty"`
	U              float64 `json:"u"`
	V              float64 `json:"v"`
}

// ImageMeasurementUpdate Partial-update body for PUT /image-measurements/{id}. Every
// field optional. `control_point_id: null` unlinks.
type ImageMeasurementUpdate struct {
	ControlPointID *ID      `json:"control_point_id,omitempty"`
	U              *float64 `json:"u,omitempty"`
	V              *float64 `json:"v,omitempty"`
}

// Photo defines model for Photo.
type Photo struct {
	// Aspect width / height of the photo in pixels
	Aspect    float64   `json:"aspect"`
	BlobPath  *string   `json:"blob_path"`
	CreatedAt time.Time `json:"created_at"`

	// DistK1 Brown-Conrady radial distortion coefficient k1; 0 = no distortion
	DistK1 float64 `json:"dist_k1"`

	// DistK2 Brown-Conrady radial distortion coefficient k2; 0 = no distortion
	DistK2 float64 `json:"dist_k2"`

	// ID 13-character base32 server-assigned id
	ID ID `json:"id"`

	// LockDistK1 locked at zero by default; unlock to let the solver fit it
	LockDistK1    bool    `json:"lock_dist_k1"`
	LockDistK2    bool    `json:"lock_dist_k2"`
	LockPhotoAz   bool    `json:"lock_photo_az"`
	LockPhotoRoll bool    `json:"lock_photo_roll"`
	LockPhotoTilt bool    `json:"lock_photo_tilt"`
	LockSizeRad   bool    `json:"lock_size_rad"`
	MimeType      *string `json:"mime_type"`
	Opacity       float64 `json:"opacity"`

	// PhotoAz viewer-azimuth radians (CCW from -Z)
	PhotoAz float64 `json:"photo_az"`

	// PhotoRoll in-plane roll radians
	PhotoRoll float64 `json:"photo_roll"`

	// PhotoTilt viewer-altitude radians (above horizon)
	PhotoTilt float64 `json:"photo_tilt"`
	SizeBytes *int64  `json:"size_bytes"`

	// SizeRad horizontal angular subtense radians
	SizeRad float64 `json:"size_rad"`

	// StationID 13-character base32 server-assigned id
	StationID ID        `json:"station_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PhotoListItem Listing-only wrapper around Photo that adds the count of image
// measurements anchored on this photo.
type PhotoListItem struct {
	ObservationCount int   `json:"observation_count"`
	Photo            Photo `json:"photo"`
}

// PhotoPosePatch POST body for `POST /stations/{id}/photos`. Pose fields are
// required; opacity / lock_* / dist_k* default if omitted.
type PhotoPosePatch struct {
	Aspect float64 `json:"aspect"`

	// DistK1 defaults to 0 when omitted
	DistK1 *float64 `json:"dist_k1,omitempty"`
	DistK2 *float64 `json:"dist_k2,omitempty"`

	// LockDistK1 defaults to true when omitted
	LockDistK1 *bool `json:"lock_dist_k1,omitempty"`
	LockDistK2 *bool `json:"lock_dist_k2,omitempty"`

	// LockPhotoAz defaults to false when omitted
	LockPhotoAz   *bool    `json:"lock_photo_az,omitempty"`
	LockPhotoRoll *bool    `json:"lock_photo_roll,omitempty"`
	LockPhotoTilt *bool    `json:"lock_photo_tilt,omitempty"`
	LockSizeRad   *bool    `json:"lock_size_rad,omitempty"`
	Opacity       *float64 `json:"opacity,omitempty"`
	PhotoAz       float64  `json:"photo_az"`
	PhotoRoll     float64  `json:"photo_roll"`
	PhotoTilt     float64  `json:"photo_tilt"`
	SizeRad       float64  `json:"size_rad"`
}

// PhotoUpdate Partial-update body for PUT /photos/{id}. Every field is
// optional; only keys present in the body are written.
type PhotoUpdate struct {
	Aspect        *float64 `json:"aspect,omitempty"`
	DistK1        *float64 `json:"dist_k1,omitempty"`
	DistK2        *float64 `json:"dist_k2,omitempty"`
	LockDistK1    *bool    `json:"lock_dist_k1,omitempty"`
	LockDistK2    *bool    `json:"lock_dist_k2,omitempty"`
	LockPhotoAz   *bool    `json:"lock_photo_az,omitempty"`
	LockPhotoRoll *bool    `json:"lock_photo_roll,omitempty"`
	LockPhotoTilt *bool    `json:"lock_photo_tilt,omitempty"`
	LockSizeRad   *bool    `json:"lock_size_rad,omitempty"`
	Opacity       *float64 `json:"opacity,omitempty"`
	PhotoAz       *float64 `json:"photo_az,omitempty"`
	PhotoRoll     *float64 `json:"photo_roll,omitempty"`
	PhotoTilt     *float64 `json:"photo_tilt,omitempty"`
	SizeRad       *float64 `json:"size_rad,omitempty"`
}

// SessionOp defines model for SessionOp.
type SessionOp struct {
	// After Row state after the op (NULL for deletes).
	After interface{} `json:"after,omitempty"`

	// Before Row state before the op (NULL for inserts).
	Before interface{} `json:"before,omitempty"`

	// EntityID 13-character base32 server-assigned id
	EntityID   ID                  `json:"entity_id"`
	EntityType SessionOpEntityType `json:"entity_type"`
	Op         SessionOpOp         `json:"op"`
	Seq        int64               `json:"seq"`
}

// SessionOpEntityType defines model for SessionOp.EntityType.
type SessionOpEntityType string

// SessionOpOp defines model for SessionOp.Op.
type SessionOpOp string

// SessionState defines model for SessionState.
type SessionState struct {
	BaseSeq int64 `json:"base_seq"`

	// Conflicts Touched entities whose entity_commits.last_seq exceeds
	// base_seq — these are the entities that block a merge.
	Conflicts []EntityRef `json:"conflicts"`
	CreatedAt time.Time   `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID      ID    `json:"id"`
	NextSeq int64 `json:"next_seq"`

	// OpCount number of journaled ops (= next_seq - 1)
	OpCount         int64              `json:"op_count"`
	Status          SessionStateStatus `json:"status"`
	TouchedEntities []EntityRef        `json:"touched_entities"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

// SessionStateStatus defines model for SessionState.Status.
type SessionStateStatus string

// SolveConfig Optional knobs for the solver. Defaults are used when omitted.
type SolveConfig struct {
	// DryRun When true, run the solver but skip the DB writeback. The response
	// still carries iterations, residuals, auto_locked_columns, and the
	// diff that would have been applied. Useful for diagnosis.
	DryRun *bool `json:"dry_run,omitempty"`

	// KRegLambda Tikhonov regularization weight on photo dist_k1 / dist_k2 lens-distortion slots (default 0.05; pass any negative value to disable
	KRegLambda *float64 `json:"k_reg_lambda,omitempty"`

	// MaxIters GN iteration cap (synchronous default 30
	MaxIters *int `json:"max_iters,omitempty"`

	// RelImproveTol per-iteration fractional reduction in residual RMS below which the run is considered converged (default 1e-4); push smaller for tighter convergence at the cost of more iterations
	RelImproveTol *float64 `json:"rel_improve_tol,omitempty"`

	// ResidualTolRad per-residual-RMS convergence threshold
	ResidualTolRad *float64 `json:"residual_tol_rad,omitempty"`
}

// SolveResult defines model for SolveResult.
type SolveResult struct {
	// AutoLockedColumns Free parameters whose Jacobian column was effectively zero — usually
	// an unobservable parameter (e.g. est_alt of a CP only seen by one
	// station). The solver pinned them for this run.
	AutoLockedColumns *[]string      `json:"auto_locked_columns,omitempty"`
	Changes           []EntityChange `json:"changes"`

	// Converged residual or step tolerance reached
	Converged bool `json:"converged"`

	// Diverged solver could not improve the initial residual; no changes were applied
	Diverged           bool    `json:"diverged"`
	FinalResidualRms   float64 `json:"final_residual_rms"`
	InitialResidualRms float64 `json:"initial_residual_rms"`
	Iterations         int     `json:"iterations"`
}

// Station defines model for Station.
type Station struct {
	// Alt meters above sea level (defaults to 0 when unknown)
	Alt float64 `json:"alt"`

	// CapturedAt when the photographer's camera was set up at this site
	CapturedAt time.Time `json:"captured_at"`
	CreatedAt  time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID  ID      `json:"id"`
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`

	// LockAlt when true the solver treats alt as a fixed input
	LockAlt bool `json:"lock_alt"`

	// LockLat when true the solver leaves lat untouched
	LockLat bool `json:"lock_lat"`

	// LockLng when true the solver leaves lng untouched
	LockLng   bool      `json:"lock_lng"`
	Name      *string   `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// StationUpdate Partial-update body for PUT /stations/{id}. Every field is
// optional; only keys present in the body are written. Sending
// `name: null` clears the name. `captured_at`, when present,
// must be a non-null date-time.
type StationUpdate struct {
	Alt        *float64   `json:"alt,omitempty"`
	CapturedAt *time.Time `json:"captured_at,omitempty"`
	Lat        *float64   `json:"lat,omitempty"`
	Lng        *float64   `json:"lng,omitempty"`
	LockAlt    *bool      `json:"lock_alt,omitempty"`
	LockLat    *bool      `json:"lock_lat,omitempty"`
	LockLng    *bool      `json:"lock_lng,omitempty"`
	Name       *string    `json:"name,omitempty"`
}

// CPConstraintID 13-character base32 server-assigned id
type CPConstraintID = ID

// CPSurfaceID 13-character base32 server-assigned id
type CPSurfaceID = ID

// ControlPointID 13-character base32 server-assigned id
type ControlPointID = ID

// ImageMeasurementID 13-character base32 server-assigned id
type ImageMeasurementID = ID

// PhotoID 13-character base32 server-assigned id
type PhotoID = ID

// StationID 13-character base32 server-assigned id
type StationID = ID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListCommitsParams defines parameters for ListCommits.
type ListCommitsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// BeforeSeq Return commits whose seq is strictly less than this value (cursor pagination).
	BeforeSeq *int `form:"before_seq,omitempty" json:"before_seq,omitempty"`
}

// ListControlPointsParams defines parameters for ListControlPoints.
type ListControlPointsParams struct {
	// Bbox Bounding box as `minLng,minLat,maxLng,maxLat`. Filter is
	// applied to the CPs' est_lat/est_lng — CPs with NULL
	// estimates are excluded when bbox is set. Returns up to 1000.
	Bbox *string `form:"bbox,omitempty" json:"bbox,omitempty"`
}

// ListStationsParams defines parameters for ListStations.
type ListStationsParams struct {
	// Bbox Bounding box as `minLng,minLat,maxLng,maxLat` (four
	// comma-separated floats). When omitted, returns up to 1000
	// stations ordered by created_at DESC.
	Bbox *string `form:"bbox,omitempty" json:"bbox,omitempty"`
}

// RevertCommitJSONRequestBody defines body for RevertCommit for application/json ContentType.
type RevertCommitJSONRequestBody = CommitMessage

// CreateCPConstraintJSONRequestBody defines body for CreateCPConstraint for application/json ContentType.
type CreateCPConstraintJSONRequestBody = CPConstraintCreate

// UpdateCPConstraintJSONRequestBody defines body for UpdateCPConstraint for application/json ContentType.
type UpdateCPConstraintJSONRequestBody = CPConstraintPatch

// CreateCPSurfaceJSONRequestBody defines body for CreateCPSurface for application/json ContentType.
type CreateCPSurfaceJSONRequestBody = CPSurfaceCreate

// CreateControlPointJSONRequestBody defines body for CreateControlPoint for application/json ContentType.
type CreateControlPointJSONRequestBody = ControlPointPatch

// UpdateControlPointJSONRequestBody defines body for UpdateControlPoint for application/json ContentType.
type UpdateControlPointJSONRequestBody = ControlPointPatch

// UpdateImageMeasurementJSONRequestBody defines body for UpdateImageMeasurement for application/json ContentType.
type UpdateImageMeasurementJSONRequestBody = ImageMeasurementUpdate

// UpdatePhotoJSONRequestBody defines body for UpdatePhoto for application/json ContentType.
type UpdatePhotoJSONRequestBody = PhotoUpdate

// CreateImageMeasurementJSONRequestBody defines body for CreateImageMeasurement for application/json ContentType.
type CreateImageMeasurementJSONRequestBody = ImageMeasurementPatch

// MergeSessionJSONRequestBody defines body for MergeSession for application/json ContentType.
type MergeSessionJSONRequestBody = CommitMessage

// SolveControlPointJSONRequestBody defines body for SolveControlPoint for application/json ContentType.
type SolveControlPointJSONRequestBody = SolveConfig

// SolveJointJSONRequestBody defines body for SolveJoint for application/json ContentType.
type SolveJointJSONRequestBody = SolveConfig

// SolveStationJSONRequestBody defines body for SolveStation for application/json ContentType.
type SolveStationJSONRequestBody = SolveConfig

// CreateStationJSONRequestBody defines body for CreateStation for application/json ContentType.
type CreateStationJSONRequestBody = CreateStationRequest

// UpdateStationJSONRequestBody defines body for UpdateStation for application/json ContentType.
type UpdateStationJSONRequestBody = StationUpdate

// CreatePhotoJSONRequestBody defines body for CreatePhoto for application/json ContentType.
type CreatePhotoJSONRequestBody = PhotoPosePatch
