// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package main

import (
	"time"
)

// ControlPoint A real-world landmark with a latent location. May be referenced
// by image measurements (across photos / stations) and map
// measurements. The estimated location (est_lat / est_lng /
// est_alt) is updated by the solver as observations accumulate;
// for v1 the estimate mirrors any linked map measurement.
type ControlPoint struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`

	// EndedAt when the landmark ceased to exist
	EndedAt *time.Time `json:"ended_at"`

	// EstAlt meters above sea level
	EstAlt *float64 `json:"est_alt"`
	EstLat *float64 `json:"est_lat"`
	EstLng *float64 `json:"est_lng"`

	// ID 13-character base32 server-assigned id
	ID ID `json:"id"`

	// Notes free-form prose describing the control point in detail
	Notes string `json:"notes"`

	// StartedAt when the landmark began existing
	StartedAt *time.Time `json:"started_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// ControlPointImageObservation defines model for ControlPointImageObservation.
type ControlPointImageObservation struct {
	Aspect float64 `json:"aspect"`

	// ID 13-character base32 server-assigned id
	ID      ID      `json:"id"`
	PhotoAz float64 `json:"photo_az"`

	// PhotoID 13-character base32 server-assigned id
	PhotoID   ID      `json:"photo_id"`
	PhotoRoll float64 `json:"photo_roll"`
	PhotoTilt float64 `json:"photo_tilt"`
	SizeRad   float64 `json:"size_rad"`

	// StationID 13-character base32 server-assigned id
	StationID   ID      `json:"station_id"`
	StationLat  float64 `json:"station_lat"`
	StationLng  float64 `json:"station_lng"`
	StationName *string `json:"station_name"`
	U           float64 `json:"u"`
	V           float64 `json:"v"`
}

// ControlPointMapObservation defines model for ControlPointMapObservation.
type ControlPointMapObservation struct {
	// ID 13-character base32 server-assigned id
	ID  ID      `json:"id"`
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`

	// StationID 13-character base32 server-assigned id
	StationID   ID      `json:"station_id"`
	StationName *string `json:"station_name"`
}

// ControlPointObservations defines model for ControlPointObservations.
type ControlPointObservations struct {
	ImageMeasurements []ControlPointImageObservation `json:"image_measurements"`
	MapMeasurements   []ControlPointMapObservation   `json:"map_measurements"`
}

// ControlPointPatch defines model for ControlPointPatch.
type ControlPointPatch struct {
	Description *string    `json:"description,omitempty"`
	EndedAt     *time.Time `json:"ended_at,omitempty"`
	EstAlt      *float64   `json:"est_alt,omitempty"`
	EstLat      *float64   `json:"est_lat,omitempty"`
	EstLng      *float64   `json:"est_lng,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
	StartedAt   *time.Time `json:"started_at,omitempty"`
}

// CreateStationRequest defines model for CreateStationRequest.
type CreateStationRequest struct {
	Lat  float64 `json:"lat"`
	Lng  float64 `json:"lng"`
	Name *string `json:"name,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// HydratedStation defines model for HydratedStation.
type HydratedStation struct {
	// ControlPoints Control points reachable from this station — i.e., those
	// referenced by at least one of this station's measurements.
	// Other CPs (in other stations) are not included.
	ControlPoints     []ControlPoint     `json:"control_points"`
	ImageMeasurements []ImageMeasurement `json:"image_measurements"`
	MapMeasurements   []MapMeasurement   `json:"map_measurements"`
	Photos            []Photo            `json:"photos"`
	Station           Station            `json:"station"`
}

// ID 13-character base32 server-assigned id
type ID = string

// ImageMeasurement Reticle anchor on a photo at (u, v): the user identifies that
// some control point is visible at this image-space position.
type ImageMeasurement struct {
	ControlPointID *ID       `json:"control_point_id"`
	CreatedAt      time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID ID `json:"id"`

	// PhotoID 13-character base32 server-assigned id
	PhotoID   ID        `json:"photo_id"`
	U         float64   `json:"u"`
	UpdatedAt time.Time `json:"updated_at"`
	V         float64   `json:"v"`
}

// ImageMeasurementPatch defines model for ImageMeasurementPatch.
type ImageMeasurementPatch struct {
	ControlPointID *ID     `json:"control_point_id,omitempty"`
	U              float64 `json:"u"`
	V              float64 `json:"v"`
}

// MapMeasurement User-asserted ground-truth observation: the user clicked on the
// map and asserts that some control point is here.
type MapMeasurement struct {
	ControlPointID *ID       `json:"control_point_id"`
	CreatedAt      time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID  ID      `json:"id"`
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`

	// StationID 13-character base32 server-assigned id
	StationID ID        `json:"station_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// MapMeasurementRequest defines model for MapMeasurementRequest.
type MapMeasurementRequest struct {
	ControlPointID *ID     `json:"control_point_id,omitempty"`
	Lat            float64 `json:"lat"`
	Lng            float64 `json:"lng"`
}

// Photo defines model for Photo.
type Photo struct {
	// Aspect width / height of the photo in pixels
	Aspect    float64   `json:"aspect"`
	BlobPath  *string   `json:"blob_path"`
	CreatedAt time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID       ID      `json:"id"`
	MimeType *string `json:"mime_type"`
	Opacity  float64 `json:"opacity"`

	// PhotoAz viewer-azimuth radians (CCW from -Z)
	PhotoAz float64 `json:"photo_az"`

	// PhotoRoll in-plane roll radians
	PhotoRoll float64 `json:"photo_roll"`

	// PhotoTilt viewer-altitude radians (above horizon)
	PhotoTilt float64 `json:"photo_tilt"`
	SizeBytes *int64  `json:"size_bytes"`

	// SizeRad horizontal angular subtense radians
	SizeRad float64 `json:"size_rad"`

	// StationID 13-character base32 server-assigned id
	StationID ID        `json:"station_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// PhotoPosePatch defines model for PhotoPosePatch.
type PhotoPosePatch struct {
	Aspect    float64  `json:"aspect"`
	Opacity   *float64 `json:"opacity,omitempty"`
	PhotoAz   float64  `json:"photo_az"`
	PhotoRoll float64  `json:"photo_roll"`
	PhotoTilt float64  `json:"photo_tilt"`
	SizeRad   float64  `json:"size_rad"`
}

// Station defines model for Station.
type Station struct {
	CreatedAt time.Time `json:"created_at"`

	// ID 13-character base32 server-assigned id
	ID        ID        `json:"id"`
	Lat       float64   `json:"lat"`
	Lng       float64   `json:"lng"`
	Name      *string   `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ControlPointID 13-character base32 server-assigned id
type ControlPointID = ID

// ImageMeasurementID 13-character base32 server-assigned id
type ImageMeasurementID = ID

// MapMeasurementID 13-character base32 server-assigned id
type MapMeasurementID = ID

// PhotoID 13-character base32 server-assigned id
type PhotoID = ID

// StationID 13-character base32 server-assigned id
type StationID = ID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListControlPointsParams defines parameters for ListControlPoints.
type ListControlPointsParams struct {
	// Bbox Bounding box as `minLng,minLat,maxLng,maxLat`. Filter is
	// applied to the CPs' est_lat/est_lng — CPs with NULL
	// estimates are excluded when bbox is set. Returns up to 1000.
	Bbox *string `form:"bbox,omitempty" json:"bbox,omitempty"`
}

// ListStationsParams defines parameters for ListStations.
type ListStationsParams struct {
	// Bbox Bounding box as `minLng,minLat,maxLng,maxLat` (four
	// comma-separated floats). When omitted, returns up to 1000
	// stations ordered by created_at DESC.
	Bbox *string `form:"bbox,omitempty" json:"bbox,omitempty"`
}

// CreateControlPointJSONRequestBody defines body for CreateControlPoint for application/json ContentType.
type CreateControlPointJSONRequestBody = ControlPointPatch

// UpdateControlPointJSONRequestBody defines body for UpdateControlPoint for application/json ContentType.
type UpdateControlPointJSONRequestBody = ControlPointPatch

// UpdateImageMeasurementJSONRequestBody defines body for UpdateImageMeasurement for application/json ContentType.
type UpdateImageMeasurementJSONRequestBody = ImageMeasurementPatch

// UpdateMapMeasurementJSONRequestBody defines body for UpdateMapMeasurement for application/json ContentType.
type UpdateMapMeasurementJSONRequestBody = MapMeasurementRequest

// UpdatePhotoJSONRequestBody defines body for UpdatePhoto for application/json ContentType.
type UpdatePhotoJSONRequestBody = PhotoPosePatch

// CreateImageMeasurementJSONRequestBody defines body for CreateImageMeasurement for application/json ContentType.
type CreateImageMeasurementJSONRequestBody = ImageMeasurementPatch

// CreateStationJSONRequestBody defines body for CreateStation for application/json ContentType.
type CreateStationJSONRequestBody = CreateStationRequest

// UpdateStationJSONRequestBody defines body for UpdateStation for application/json ContentType.
type UpdateStationJSONRequestBody = CreateStationRequest

// CreateMapMeasurementJSONRequestBody defines body for CreateMapMeasurement for application/json ContentType.
type CreateMapMeasurementJSONRequestBody = MapMeasurementRequest

// CreatePhotoJSONRequestBody defines body for CreatePhoto for application/json ContentType.
type CreatePhotoJSONRequestBody = PhotoPosePatch
