/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DB-backed liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locations, optionally filtered by bbox */
        get: operations["listLocations"];
        put?: never;
        /** Create a project location */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        /** Get a location with its photos, map POIs, and image POIs */
        get: operations["getLocation"];
        /** Update a location's lat/lng/name */
        put: operations["updateLocation"];
        post?: never;
        /**
         * Delete a location and cascade
         * @description Cascades to photos and image POIs in the database, and removes
         *     photo blob files from disk.
         */
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a photo on a location (metadata only)
         * @description Creates a photo row with an empty blob slot. Upload the image bytes
         *     via `PUT /photos/{id}/blob` afterwards.
         */
        post: operations["createPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Get photo metadata */
        get: operations["getPhoto"];
        /** Update photo pose / opacity / aspect */
        put: operations["updatePhoto"];
        post?: never;
        /** Delete a photo (and its blob) */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Download the photo's image blob */
        get: operations["getPhotoBlob"];
        /** Upload the photo's image blob */
        put: operations["uploadPhotoBlob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/map-pois": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a map POI on a location */
        post: operations["createMapPOI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map-pois/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MapPOIId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Move a map POI */
        put: operations["updateMapPOI"];
        post?: never;
        /**
         * Delete a map POI
         * @description Cascades `ON DELETE SET NULL` on `image_pois.map_poi_id` —
         *     anchored image POIs survive but lose their link.
         */
        delete: operations["deleteMapPOI"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/image-pois": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an image POI on a photo */
        post: operations["createImagePOI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image-pois/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImagePOIId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update an image POI's u/v or anchor */
        put: operations["updateImagePOI"];
        post?: never;
        /** Delete an image POI */
        delete: operations["deleteImagePOI"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 13-character base32 server-assigned id */
        Id: string;
        Health: {
            /** @example ok */
            status: string;
        };
        Error: {
            error: string;
        };
        Location: {
            id: components["schemas"]["Id"];
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            name: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Photo: {
            id: components["schemas"]["Id"];
            location_id: components["schemas"]["Id"];
            blob_path: string | null;
            mime_type: string | null;
            /** Format: int64 */
            size_bytes: number | null;
            /**
             * Format: double
             * @description width / height of the photo in pixels
             */
            aspect: number;
            /**
             * Format: double
             * @description viewer-azimuth radians (CCW from -Z)
             */
            photo_az: number;
            /**
             * Format: double
             * @description viewer-altitude radians (above horizon)
             */
            photo_tilt: number;
            /**
             * Format: double
             * @description in-plane roll radians
             */
            photo_roll: number;
            /**
             * Format: double
             * @description horizontal angular subtense radians
             */
            size_rad: number;
            /** Format: double */
            opacity: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MapPOI: {
            id: components["schemas"]["Id"];
            location_id: components["schemas"]["Id"];
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ImagePOI: {
            id: components["schemas"]["Id"];
            photo_id: components["schemas"]["Id"];
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            map_poi_id: components["schemas"]["Id"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        HydratedLocation: {
            location: components["schemas"]["Location"];
            photos: components["schemas"]["Photo"][];
            map_pois: components["schemas"]["MapPOI"][];
            image_pois: components["schemas"]["ImagePOI"][];
        };
        CreateLocationRequest: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            name?: string | null;
        };
        PhotoPosePatch: {
            /** Format: double */
            aspect: number;
            /** Format: double */
            photo_az: number;
            /** Format: double */
            photo_tilt: number;
            /** Format: double */
            photo_roll: number;
            /** Format: double */
            size_rad: number;
            /** Format: double */
            opacity?: number;
        };
        MapPOIRequest: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        ImagePOIPatch: {
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            map_poi_id?: components["schemas"]["Id"] | null;
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        LocationId: components["schemas"]["Id"];
        PhotoId: components["schemas"]["Id"];
        MapPOIId: components["schemas"]["Id"];
        ImagePOIId: components["schemas"]["Id"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description DB unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                /**
                 * @description Bounding box as `minLng,minLat,maxLng,maxLat` (four
                 *     comma-separated floats). When omitted, returns up to 1000
                 *     locations ordered by created_at DESC.
                 */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HydratedLocation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoPosePatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoPosePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPhotoBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadPhotoBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/*": string;
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Payload too large (above MAX_BLOB_BYTES) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createMapPOI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapPOIRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapPOI"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMapPOI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MapPOIId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapPOIRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapPOI"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteMapPOI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MapPOIId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createImagePOI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePOIPatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePOI"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateImagePOI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImagePOIId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePOIPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePOI"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteImagePOI: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImagePOIId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
