/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DB-backed liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stations, optionally filtered by bbox */
        get: operations["listStations"];
        put?: never;
        /** Create a station */
        post: operations["createStation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        /** Get a station with its photos, measurements, and referenced control points */
        get: operations["getStation"];
        /**
         * Partial-update a station
         * @description Partial update: only the keys present in the request body are
         *     written. Omitting a key preserves its current value; sending an
         *     explicit `null` clears nullable columns (e.g. `name`).
         */
        put: operations["updateStation"];
        post?: never;
        /**
         * Delete a station and cascade
         * @description Cascades to photos and image measurements in the database, and
         *     removes photo blob files from disk. Control points referenced
         *     only from the deleted station are NOT cascade-deleted (they
         *     live cross-station) — they survive without measurements until
         *     explicitly removed.
         */
        delete: operations["deleteStation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stations/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a photo on a station (metadata only)
         * @description Creates a photo row with an empty blob slot. Upload the image bytes
         *     via `PUT /photos/{id}/blob` afterwards.
         */
        post: operations["createPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all photos with per-photo observation counts
         * @description Returns every photo in the system (or session overlay when an
         *     `X-Session-Id` header is set), ordered by created_at ASC. Each
         *     item also carries `observation_count` — the number of image
         *     measurements anchored on that photo (counted from the main DB
         *     only, so in-session inserts/deletes are not reflected).
         */
        get: operations["listPhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Get photo metadata */
        get: operations["getPhoto"];
        /**
         * Partial-update photo pose / opacity / aspect / locks
         * @description Partial update: only the keys present in the request body are
         *     written. Omitting a key preserves its current value.
         */
        put: operations["updatePhoto"];
        post?: never;
        /** Delete a photo (and its blob) */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Download the photo's image blob */
        get: operations["getPhotoBlob"];
        /** Upload the photo's image blob */
        put: operations["uploadPhotoBlob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/image-measurements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an image measurement on a photo */
        post: operations["createImageMeasurement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image-measurements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageMeasurementId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Partial-update an image measurement's u/v or control point link
         * @description Partial update: only the keys present in the request body are
         *     written. Sending `control_point_id: null` unlinks the measurement
         *     from its control point.
         */
        put: operations["updateImageMeasurement"];
        post?: never;
        /** Delete an image measurement */
        delete: operations["deleteImageMeasurement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List control points, optionally filtered by bbox */
        get: operations["listControlPoints"];
        put?: never;
        /**
         * Create a control point
         * @description Control points are global (cross-station). Initial est_lat /
         *     est_lng / est_alt are optional; a CP without estimates is
         *     a "latent" landmark whose location is unknown until the solver
         *     triangulates from observations.
         */
        post: operations["createControlPoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        /** Get a control point */
        get: operations["getControlPoint"];
        /** Update a control point's description / estimates */
        put: operations["updateControlPoint"];
        post?: never;
        /**
         * Delete a control point
         * @description Cascades `ON DELETE SET NULL` on referencing image and map
         *     measurements; both survive without their link.
         */
        delete: operations["deleteControlPoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-point-fits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List per-CP goodness-of-fit (angular residual RMS)
         * @description For every control point with a known est_lat/est_lng and at least
         *     one image measurement, returns the RMS angular residual between
         *     each observation's ray and the bearing from its station to the
         *     stored estimate. Same residual definition the solver minimizes.
         *     Surfaces a "two locations conflated into one CP" signal: tiny
         *     residuals mean observations agree on a single point; large ones
         *     mean they don't. est_alt NULL is treated as 0 (matches the
         *     solver). CPs without observations are omitted.
         */
        get: operations["listControlPointFits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-point-constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all pairwise control-point constraints */
        get: operations["listCPConstraints"];
        put?: never;
        /**
         * Create a pairwise constraint between two control points
         * @description Creates a hard equality constraint between two control points.
         *     The handler swaps `cp_a_id` and `cp_b_id` if necessary so the
         *     stored row satisfies the canonical `cp_a_id < cp_b_id` ordering.
         *     Self-loops (same id on both sides) and duplicate (a, b, type)
         *     triples are rejected.
         *
         *     Type semantics:
         *       * `plumb` — the two CPs share `est_lat` and `est_lng`
         *       * `level` — the two CPs share `est_alt`
         */
        post: operations["createCPConstraint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-point-constraints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CPConstraintId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Change the constraint type */
        put: operations["updateCPConstraint"];
        post?: never;
        /** Delete a constraint */
        delete: operations["deleteCPConstraint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-point-surfaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all CP surfaces */
        get: operations["listCPSurfaces"];
        put?: never;
        /**
         * Create a polygonal surface anchored on 3 or 4 control points
         * @description Creates a triangle (3 distinct CP ids) or quad (4 distinct CP ids) surface
         *     for visualization in the 3D world view. The four CP ids must be pairwise
         *     distinct; `cp_4_id` omitted or null yields a triangle. Surfaces have no
         *     editable fields after creation — modify by deleting and recreating.
         */
        post: operations["createCPSurface"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-point-surfaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CPSurfaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a surface */
        delete: operations["deleteCPSurface"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve/joint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bundle-adjust the entire system (stations + photos + control points)
         * @description Runs Gauss-Newton over every unlocked solvable parameter across all
         *     stations, photos, and control points. Requires at least two stations
         *     with both lat and lng locked (translation + rotation gauge); returns
         *     400 otherwise. Persists the result inside one transaction; uses
         *     optimistic concurrency on each row's `updated_at` and returns 409 if
         *     another writer raced the solve.
         */
        post: operations["solveJoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve/stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine the photo poses of a single station
         * @description Solves the joint photo-pose problem for the given station, treating
         *     the station's own lat/lng and every control point's est_* as fixed.
         *     No gauge requirement (the station is the implicit anchor).
         */
        post: operations["solveStation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solve/control-points/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine est_lat / est_lng / est_alt for a single control point
         * @description Triangulates the CP location from its image measurements across
         *     stations. Requires at least two image observations.
         */
        post: operations["solveControlPoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points/{id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        /**
         * List every observation referencing this control point
         * @description Returns image measurements across every station that link back
         *     to the given control point. Each row carries enough context
         *     (station id + name) for the caller to deep-link.
         */
        get: operations["listControlPointObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a new session at HEAD
         * @description Sessions are server-issued anonymous workspaces. The id returned
         *     here is what the client persists in localStorage and sends back as
         *     `X-Session-Id` on every subsequent read/write to scope reads to the
         *     session overlay and writes to the journal.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** Session metadata + ops summary + live conflict list */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/ops": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** Full journal of ops in seq order */
        get: operations["getSessionOps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a session as abandoned
         * @description Idempotent: returns 204 if already abandoned. Refuses with 409 if
         *     the session is merged (history is immutable).
         */
        post: operations["abandonSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Promote the session to a new commit on main
         * @description Coalesces session ops per entity, applies them to main inside one
         *     SERIALIZABLE transaction, and writes a new commit row referencing
         *     this session. Refuses with 409 if any entity touched by the
         *     session has been modified by a commit since the session's base.
         */
        post: operations["mergeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List commits, latest first */
        get: operations["listCommits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        /** One commit row plus the journaled ops it landed */
        get: operations["getCommit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/commits/{id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new commit that inverts the target's effect
         * @description Walks the target commit's journal backward, swaps before/after on
         *     each op, and applies the inverse plan to main. Refuses with 409 if
         *     any later commit has touched any of the target's entities.
         */
        post: operations["revertCommit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points/{id}/visible-photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        /**
         * List photos whose viewshed should contain this control point
         * @description Returns photos where the CP's estimated location falls inside the
         *     photo's horizontal field of view AND the station's capture time
         *     falls inside the CP's lifespan AND no image measurement for this
         *     CP exists yet on the photo. The result is the inverse of the
         *     observations list — candidate photos still missing a measurement.
         *
         *     Returns an empty list (200) when the CP has no estimated
         *     location; the caller decides how to render that state.
         */
        get: operations["listControlPointVisiblePhotos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 13-character base32 server-assigned id */
        Id: string;
        Health: {
            /** @example ok */
            status: string;
        };
        Error: {
            error: string;
        };
        Station: {
            id: components["schemas"]["Id"];
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /**
             * Format: double
             * @description meters above sea level (defaults to 0 when unknown)
             */
            alt: number;
            name: string | null;
            /** @description when true the solver leaves lat untouched */
            lock_lat: boolean;
            /** @description when true the solver leaves lng untouched */
            lock_lng: boolean;
            /** @description when true the solver treats alt as a fixed input */
            lock_alt: boolean;
            /**
             * Format: date-time
             * @description when the photographer's camera was set up at this site
             */
            captured_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Photo: {
            id: components["schemas"]["Id"];
            station_id: components["schemas"]["Id"];
            blob_path: string | null;
            mime_type: string | null;
            /** Format: int64 */
            size_bytes: number | null;
            /**
             * Format: double
             * @description width / height of the photo in pixels
             */
            aspect: number;
            /**
             * Format: double
             * @description viewer-azimuth radians (CCW from -Z)
             */
            photo_az: number;
            /**
             * Format: double
             * @description viewer-altitude radians (above horizon)
             */
            photo_tilt: number;
            /**
             * Format: double
             * @description in-plane roll radians
             */
            photo_roll: number;
            /**
             * Format: double
             * @description horizontal angular subtense radians
             */
            size_rad: number;
            /** Format: double */
            opacity: number;
            lock_photo_az: boolean;
            lock_photo_tilt: boolean;
            lock_photo_roll: boolean;
            lock_size_rad: boolean;
            /**
             * Format: double
             * @description Brown-Conrady radial distortion coefficient k1; 0 = no distortion
             */
            dist_k1: number;
            /**
             * Format: double
             * @description Brown-Conrady radial distortion coefficient k2; 0 = no distortion
             */
            dist_k2: number;
            /** @description locked at zero by default; unlock to let the solver fit it */
            lock_dist_k1: boolean;
            lock_dist_k2: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Listing-only wrapper around Photo that adds the count of image
         *     measurements anchored on this photo.
         */
        PhotoListItem: {
            photo: components["schemas"]["Photo"];
            observation_count: number;
        };
        /**
         * @description Reticle anchor on a photo at (u, v): the user identifies that
         *     some control point is visible at this image-space position.
         */
        ImageMeasurement: {
            id: components["schemas"]["Id"];
            photo_id: components["schemas"]["Id"];
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            control_point_id: components["schemas"]["Id"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description A real-world landmark with a user-seeded location estimate
         *     (est_lat / est_lng / est_alt) and image-measurement observations
         *     across photos and stations. The estimate is set when the CP is
         *     created and refined by the location solver as observations accumulate.
         */
        ControlPoint: {
            id: components["schemas"]["Id"];
            description: string;
            /** @description free-form prose describing the control point in detail */
            notes: string;
            /** Format: double */
            est_lat: number | null;
            /** Format: double */
            est_lng: number | null;
            /**
             * Format: double
             * @description meters above sea level; null when the elevation isn't known
             */
            est_alt: number | null;
            /**
             * Format: date-time
             * @description when the landmark began existing
             */
            started_at: string | null;
            /**
             * Format: date-time
             * @description when the landmark ceased to exist
             */
            ended_at: string | null;
            /** @description when true */
            started_after: boolean;
            /** @description when true */
            ended_before: boolean;
            lock_est_lat: boolean;
            lock_est_lng: boolean;
            lock_est_alt: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ControlPointImageObservation: {
            id: components["schemas"]["Id"];
            photo_id: components["schemas"]["Id"];
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            station_id: components["schemas"]["Id"];
            station_name: string | null;
            /** Format: double */
            station_lat: number;
            /** Format: double */
            station_lng: number;
            /** Format: date-time */
            station_captured_at: string;
            /** Format: double */
            photo_az: number;
            /** Format: double */
            photo_tilt: number;
            /** Format: double */
            photo_roll: number;
            /** Format: double */
            size_rad: number;
            /** Format: double */
            aspect: number;
        };
        ControlPointObservations: {
            image_measurements: components["schemas"]["ControlPointImageObservation"][];
        };
        /**
         * @description A photo whose horizontal viewshed contains the CP's estimated
         *     location and whose station capture time overlaps the CP's
         *     lifespan, but which has no image measurement linking to the CP
         *     yet. Pose and station coordinates used for the server-side
         *     viewshed test are intentionally not exposed.
         */
        ControlPointVisiblePhoto: {
            photo_id: components["schemas"]["Id"];
            station_id: components["schemas"]["Id"];
            station_name: string | null;
            /** Format: date-time */
            station_captured_at: string;
        };
        ControlPointVisiblePhotos: {
            photos: components["schemas"]["ControlPointVisiblePhoto"][];
        };
        /**
         * @description Goodness-of-fit summary for one CP. fit_rms_rad is the RMS angular
         *     residual (radians) between every observation's image-plane ray and
         *     the bearing from its station to the CP's stored estimate — same
         *     residual the solver minimizes. observation_count is the number of
         *     image measurements that contributed.
         */
        ControlPointFit: {
            id: components["schemas"]["Id"];
            /** Format: double */
            fit_rms_rad: number;
            observation_count: number;
        };
        ControlPointFits: {
            control_points: components["schemas"]["ControlPointFit"][];
        };
        HydratedStation: {
            station: components["schemas"]["Station"];
            photos: components["schemas"]["Photo"][];
            image_measurements: components["schemas"]["ImageMeasurement"][];
            /**
             * @description Control points reachable from this station — i.e., those
             *     referenced by at least one of this station's measurements.
             *     Other CPs (in other stations) are not included.
             */
            control_points: components["schemas"]["ControlPoint"][];
        };
        /** @description POST body. lat/lng/captured_at are required; other fields default if omitted. */
        CreateStationRequest: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /**
             * Format: double
             * @description defaults to 0 when omitted
             */
            alt?: number;
            name?: string | null;
            /** @description defaults to false when omitted */
            lock_lat?: boolean;
            lock_lng?: boolean;
            lock_alt?: boolean;
            /** Format: date-time */
            captured_at: string;
        };
        /**
         * @description Partial-update body for PUT /stations/{id}. Every field is
         *     optional; only keys present in the body are written. Sending
         *     `name: null` clears the name. `captured_at`, when present,
         *     must be a non-null date-time.
         */
        StationUpdate: {
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            /** Format: double */
            alt?: number;
            name?: string | null;
            lock_lat?: boolean;
            lock_lng?: boolean;
            lock_alt?: boolean;
            /** Format: date-time */
            captured_at?: string;
        };
        /**
         * @description POST body for `POST /stations/{id}/photos`. Pose fields are
         *     required; opacity / lock_* / dist_k* default if omitted.
         */
        PhotoPosePatch: {
            /** Format: double */
            aspect: number;
            /** Format: double */
            photo_az: number;
            /** Format: double */
            photo_tilt: number;
            /** Format: double */
            photo_roll: number;
            /** Format: double */
            size_rad: number;
            /** Format: double */
            opacity?: number;
            /** @description defaults to false when omitted */
            lock_photo_az?: boolean;
            lock_photo_tilt?: boolean;
            lock_photo_roll?: boolean;
            lock_size_rad?: boolean;
            /**
             * Format: double
             * @description defaults to 0 when omitted
             */
            dist_k1?: number;
            /** Format: double */
            dist_k2?: number;
            /** @description defaults to true when omitted */
            lock_dist_k1?: boolean;
            lock_dist_k2?: boolean;
        };
        /**
         * @description Partial-update body for PUT /photos/{id}. Every field is
         *     optional; only keys present in the body are written.
         */
        PhotoUpdate: {
            /** Format: double */
            aspect?: number;
            /** Format: double */
            photo_az?: number;
            /** Format: double */
            photo_tilt?: number;
            /** Format: double */
            photo_roll?: number;
            /** Format: double */
            size_rad?: number;
            /** Format: double */
            opacity?: number;
            lock_photo_az?: boolean;
            lock_photo_tilt?: boolean;
            lock_photo_roll?: boolean;
            lock_size_rad?: boolean;
            /** Format: double */
            dist_k1?: number;
            /** Format: double */
            dist_k2?: number;
            lock_dist_k1?: boolean;
            lock_dist_k2?: boolean;
        };
        /**
         * @description POST body for `POST /photos/{id}/image-measurements`. u/v
         *     required; control_point_id optional (null = unlinked).
         */
        ImageMeasurementPatch: {
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            control_point_id?: components["schemas"]["Id"] | null;
        };
        /**
         * @description Partial-update body for PUT /image-measurements/{id}. Every
         *     field optional. `control_point_id: null` unlinks.
         */
        ImageMeasurementUpdate: {
            /** Format: double */
            u?: number;
            /** Format: double */
            v?: number;
            control_point_id?: components["schemas"]["Id"] | null;
        };
        /**
         * @description Body for both `POST /control-points` and `PUT
         *     /control-points/{id}`. Every field optional. On POST, omitted
         *     fields take their column defaults; on PUT, omitted fields are
         *     preserved.
         */
        ControlPointPatch: {
            description?: string;
            notes?: string;
            /** Format: double */
            est_lat?: number | null;
            /** Format: double */
            est_lng?: number | null;
            /** Format: double */
            est_alt?: number | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            started_after?: boolean;
            ended_before?: boolean;
            lock_est_lat?: boolean;
            lock_est_lng?: boolean;
            lock_est_alt?: boolean;
        };
        /**
         * @description plumb: cp_a and cp_b share est_lat and est_lng (vertical line);
         *     level: cp_a and cp_b share est_alt (horizontal alignment).
         * @enum {string}
         */
        CPConstraintType: "plumb" | "level";
        CPConstraint: {
            id: components["schemas"]["Id"];
            cp_a_id: components["schemas"]["Id"];
            cp_b_id: components["schemas"]["Id"];
            constraint_type: components["schemas"]["CPConstraintType"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description POST body for `/control-point-constraints`. The handler
         *     swaps `cp_a_id` and `cp_b_id` if needed to satisfy the
         *     canonical `cp_a_id < cp_b_id` ordering before insert.
         */
        CPConstraintCreate: {
            cp_a_id: components["schemas"]["Id"];
            cp_b_id: components["schemas"]["Id"];
            constraint_type: components["schemas"]["CPConstraintType"];
        };
        /** @description Partial-update body. Only `constraint_type` is mutable. */
        CPConstraintPatch: {
            constraint_type?: components["schemas"]["CPConstraintType"];
        };
        /**
         * @description Polygonal surface anchored on 3 (triangle, cp_4_id null) or 4 (quad)
         *     control points. Surfaces are visualization-only; the solver doesn't
         *     read them.
         */
        CPSurface: {
            id: components["schemas"]["Id"];
            cp_1_id: components["schemas"]["Id"];
            cp_2_id: components["schemas"]["Id"];
            cp_3_id: components["schemas"]["Id"];
            cp_4_id?: components["schemas"]["Id"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description POST body for `/control-point-surfaces`. cp_4_id null or omitted
         *     makes a triangle; otherwise a quad. All non-null ids must be
         *     pairwise distinct.
         */
        CPSurfaceCreate: {
            cp_1_id: components["schemas"]["Id"];
            cp_2_id: components["schemas"]["Id"];
            cp_3_id: components["schemas"]["Id"];
            cp_4_id?: components["schemas"]["Id"] | null;
        };
        /** @description Optional knobs for the solver. Defaults are used when omitted. */
        SolveConfig: {
            /** @description GN iteration cap (synchronous default 30 */
            max_iters?: number;
            /**
             * Format: double
             * @description per-residual-RMS convergence threshold
             */
            residual_tol_rad?: number;
            /**
             * Format: double
             * @description per-iteration fractional reduction in residual RMS below which the run is considered converged (default 1e-4); push smaller for tighter convergence at the cost of more iterations
             */
            rel_improve_tol?: number;
            /**
             * Format: double
             * @description Tikhonov regularization weight on photo dist_k1 / dist_k2 lens-distortion slots (default 0.05; pass any negative value to disable
             */
            k_reg_lambda?: number;
            /**
             * @description When true, run the solver but skip the DB writeback. The response
             *     still carries iterations, residuals, auto_locked_columns, and the
             *     diff that would have been applied. Useful for diagnosis.
             */
            dry_run?: boolean;
        };
        /** @description One row's before/after for the keys the solver actually moved. */
        EntityChange: {
            /** @enum {string} */
            kind: "station" | "photo" | "control_point";
            id: components["schemas"]["Id"];
            before: {
                [key: string]: number;
            };
            after: {
                [key: string]: number;
            };
        };
        CreateSessionResponse: {
            id: components["schemas"]["Id"];
            /**
             * Format: int64
             * @description HEAD seq the session forked from (0 if commit log is empty)
             */
            base_seq: number;
            /** @enum {string} */
            status: "open" | "merged" | "abandoned";
            /**
             * Format: int64
             * @description Next per-session op sequence to be assigned
             */
            next_seq: number;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description One entity touched by a session, optionally annotated with the
         *     last-commit seq that updated it on main.
         */
        EntityRef: {
            /** @enum {string} */
            entity_type: "station" | "photo" | "image_measurement" | "control_point" | "cp_constraint" | "cp_surface";
            entity_id: components["schemas"]["Id"];
            /** Format: int64 */
            last_seq?: number | null;
        };
        SessionState: {
            id: components["schemas"]["Id"];
            /** Format: int64 */
            base_seq: number;
            /** @enum {string} */
            status: "open" | "merged" | "abandoned";
            /** Format: int64 */
            next_seq: number;
            /**
             * Format: int64
             * @description number of journaled ops (= next_seq - 1)
             */
            op_count: number;
            touched_entities: components["schemas"]["EntityRef"][];
            /**
             * @description Touched entities whose entity_commits.last_seq exceeds
             *     base_seq — these are the entities that block a merge.
             */
            conflicts: components["schemas"]["EntityRef"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SessionOp: {
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            entity_type: "station" | "photo" | "image_measurement" | "control_point" | "cp_constraint" | "cp_surface";
            entity_id: components["schemas"]["Id"];
            /** @enum {string} */
            op: "insert" | "update" | "delete";
            /** @description Row state before the op (NULL for inserts). */
            before?: unknown;
            /** @description Row state after the op (NULL for deletes). */
            after?: unknown;
        };
        CommitMessage: {
            message?: string;
        };
        MergeRequest: {
            sign_off: string;
            message?: string;
        };
        CommitRef: {
            commit_id: components["schemas"]["Id"];
            /** Format: int64 */
            seq: number;
        };
        Commit: {
            id: components["schemas"]["Id"];
            /** Format: int64 */
            seq: number;
            /** Format: int64 */
            parent_seq?: number | null;
            source_session_id?: components["schemas"]["Id"] | null;
            /** @enum {string} */
            kind: "merge" | "revert";
            reverts_commit_id?: components["schemas"]["Id"] | null;
            message?: string | null;
            sign_off: string;
            /** Format: date-time */
            created_at: string;
        };
        CommitWithOps: {
            commit: components["schemas"]["Commit"];
            ops: components["schemas"]["SessionOp"][];
        };
        ConflictsResponse: {
            error: string;
            conflicts: components["schemas"]["EntityRef"][];
        };
        SolveResult: {
            iterations: number;
            /** Format: double */
            initial_residual_rms: number;
            /** Format: double */
            final_residual_rms: number;
            /** @description residual or step tolerance reached */
            converged: boolean;
            /** @description solver could not improve the initial residual; no changes were applied */
            diverged: boolean;
            /**
             * @description Free parameters whose Jacobian column was effectively zero — usually
             *     an unobservable parameter (e.g. est_alt of a CP only seen by one
             *     station). The solver pinned them for this run.
             */
            auto_locked_columns?: string[];
            changes: components["schemas"]["EntityChange"][];
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        StationId: components["schemas"]["Id"];
        PhotoId: components["schemas"]["Id"];
        ImageMeasurementId: components["schemas"]["Id"];
        ControlPointId: components["schemas"]["Id"];
        CPConstraintId: components["schemas"]["Id"];
        CPSurfaceId: components["schemas"]["Id"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description DB unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listStations: {
        parameters: {
            query?: {
                /**
                 * @description Bounding box as `minLng,minLat,maxLng,maxLat` (four
                 *     comma-separated floats). When omitted, returns up to 1000
                 *     stations ordered by created_at DESC.
                 */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Station"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createStation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Station"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getStation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HydratedStation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateStation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StationUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Station"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteStation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoPosePatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoListItem"][];
                };
            };
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPhotoBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadPhotoBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/*": string;
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Payload too large (above MAX_BLOB_BYTES) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createImageMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageMeasurementPatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMeasurement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateImageMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageMeasurementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageMeasurementUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMeasurement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteImageMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageMeasurementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listControlPoints: {
        parameters: {
            query?: {
                /**
                 * @description Bounding box as `minLng,minLat,maxLng,maxLat`. Filter is
                 *     applied to the CPs' est_lat/est_lng — CPs with NULL
                 *     estimates are excluded when bbox is set. Returns up to 1000.
                 */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPointPatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPointPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listControlPointFits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPointFits"];
                };
            };
        };
    };
    listCPConstraints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPConstraint"][];
                };
            };
        };
    };
    createCPConstraint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CPConstraintCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPConstraint"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description A constraint of this type already exists between this pair */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCPConstraint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CPConstraintId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CPConstraintPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPConstraint"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCPConstraint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CPConstraintId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCPSurfaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPSurface"][];
                };
            };
        };
    };
    createCPSurface: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CPSurfaceCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CPSurface"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCPSurface: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CPSurfaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    solveJoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SolveConfig"];
            };
        };
        responses: {
            /** @description OK (incl. divergence; check `diverged`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Concurrent edit detected; re-fetch and retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    solveStation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["StationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SolveConfig"];
            };
        };
        responses: {
            /** @description OK (incl. divergence; check `diverged`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Concurrent edit detected; re-fetch and retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    solveControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SolveConfig"];
            };
        };
        responses: {
            /** @description OK (incl. divergence; check `diverged`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Concurrent edit detected; re-fetch and retry */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listControlPointObservations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPointObservations"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSessionOps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOp"][];
                };
            };
        };
    };
    abandonSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abandoned */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Session is already merged */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mergeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeRequest"];
            };
        };
        responses: {
            /** @description Merged */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Conflict — abandon and start over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictsResponse"];
                };
            };
        };
    };
    listCommits: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return commits whose seq is strictly less than this value (cursor pagination). */
                before_seq?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Commit"][];
                };
            };
        };
    };
    getCommit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitWithOps"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    revertCommit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommitMessage"];
            };
        };
        responses: {
            /** @description Reverted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Conflict — later commits have touched these entities */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictsResponse"];
                };
            };
        };
    };
    listControlPointVisiblePhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPointVisiblePhotos"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
