/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DB-backed liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locations, optionally filtered by bbox */
        get: operations["listLocations"];
        put?: never;
        /** Create a project location */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        /** Get a location with its photos, measurements, and referenced control points */
        get: operations["getLocation"];
        /** Update a location's lat/lng/name */
        put: operations["updateLocation"];
        post?: never;
        /**
         * Delete a location and cascade
         * @description Cascades to photos and image measurements in the database, and
         *     removes photo blob files from disk. Control points referenced
         *     only from the deleted project are NOT cascade-deleted (they
         *     live cross-project) — they survive without measurements until
         *     explicitly removed.
         */
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a photo on a location (metadata only)
         * @description Creates a photo row with an empty blob slot. Upload the image bytes
         *     via `PUT /photos/{id}/blob` afterwards.
         */
        post: operations["createPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Get photo metadata */
        get: operations["getPhoto"];
        /** Update photo pose / opacity / aspect */
        put: operations["updatePhoto"];
        post?: never;
        /** Delete a photo (and its blob) */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Download the photo's image blob */
        get: operations["getPhotoBlob"];
        /** Upload the photo's image blob */
        put: operations["uploadPhotoBlob"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/map-measurements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a map measurement on a location */
        post: operations["createMapMeasurement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map-measurements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MapMeasurementId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a map measurement's lat/lng or control point link */
        put: operations["updateMapMeasurement"];
        post?: never;
        /** Delete a map measurement */
        delete: operations["deleteMapMeasurement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}/image-measurements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an image measurement on a photo */
        post: operations["createImageMeasurement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image-measurements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageMeasurementId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update an image measurement's u/v or control point link */
        put: operations["updateImageMeasurement"];
        post?: never;
        /** Delete an image measurement */
        delete: operations["deleteImageMeasurement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List control points, optionally filtered by bbox */
        get: operations["listControlPoints"];
        put?: never;
        /**
         * Create a control point
         * @description Control points are global (cross-project). Initial est_lat /
         *     est_lng / est_alt are optional; a CP without estimates is
         *     a "latent" landmark whose location is unknown until the solver
         *     triangulates from observations.
         */
        post: operations["createControlPoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        /** Get a control point */
        get: operations["getControlPoint"];
        /** Update a control point's description / estimates */
        put: operations["updateControlPoint"];
        post?: never;
        /**
         * Delete a control point
         * @description Cascades `ON DELETE SET NULL` on referencing image and map
         *     measurements; both survive without their link.
         */
        delete: operations["deleteControlPoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/control-points/{id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        /**
         * List every observation referencing this control point
         * @description Returns image and map measurements across every project that
         *     link back to the given control point. Each row carries enough
         *     context (location id + name) for the caller to deep-link.
         */
        get: operations["listControlPointObservations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 13-character base32 server-assigned id */
        Id: string;
        Health: {
            /** @example ok */
            status: string;
        };
        Error: {
            error: string;
        };
        Location: {
            id: components["schemas"]["Id"];
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            name: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Photo: {
            id: components["schemas"]["Id"];
            location_id: components["schemas"]["Id"];
            blob_path: string | null;
            mime_type: string | null;
            /** Format: int64 */
            size_bytes: number | null;
            /**
             * Format: double
             * @description width / height of the photo in pixels
             */
            aspect: number;
            /**
             * Format: double
             * @description viewer-azimuth radians (CCW from -Z)
             */
            photo_az: number;
            /**
             * Format: double
             * @description viewer-altitude radians (above horizon)
             */
            photo_tilt: number;
            /**
             * Format: double
             * @description in-plane roll radians
             */
            photo_roll: number;
            /**
             * Format: double
             * @description horizontal angular subtense radians
             */
            size_rad: number;
            /** Format: double */
            opacity: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description User-asserted ground-truth observation: the user clicked on the
         *     map and asserts that some control point is here.
         */
        MapMeasurement: {
            id: components["schemas"]["Id"];
            location_id: components["schemas"]["Id"];
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            control_point_id: components["schemas"]["Id"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Reticle anchor on a photo at (u, v): the user identifies that
         *     some control point is visible at this image-space position.
         */
        ImageMeasurement: {
            id: components["schemas"]["Id"];
            photo_id: components["schemas"]["Id"];
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            control_point_id: components["schemas"]["Id"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description A real-world landmark with a latent location. May be referenced
         *     by image measurements (across photos / projects) and map
         *     measurements. The estimated location (est_lat / est_lng /
         *     est_alt) is updated by the solver as observations accumulate;
         *     for v1 the estimate mirrors any linked map measurement.
         */
        ControlPoint: {
            id: components["schemas"]["Id"];
            description: string;
            /** Format: double */
            est_lat: number | null;
            /** Format: double */
            est_lng: number | null;
            /**
             * Format: double
             * @description meters above sea level
             */
            est_alt: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ControlPointImageObservation: {
            id: components["schemas"]["Id"];
            photo_id: components["schemas"]["Id"];
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            location_id: components["schemas"]["Id"];
            location_name: string | null;
        };
        ControlPointMapObservation: {
            id: components["schemas"]["Id"];
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            location_id: components["schemas"]["Id"];
            location_name: string | null;
        };
        ControlPointObservations: {
            image_measurements: components["schemas"]["ControlPointImageObservation"][];
            map_measurements: components["schemas"]["ControlPointMapObservation"][];
        };
        HydratedLocation: {
            location: components["schemas"]["Location"];
            photos: components["schemas"]["Photo"][];
            map_measurements: components["schemas"]["MapMeasurement"][];
            image_measurements: components["schemas"]["ImageMeasurement"][];
            /**
             * @description Control points reachable from this project — i.e., those
             *     referenced by at least one of this location's measurements.
             *     Other CPs (in other projects) are not included.
             */
            control_points: components["schemas"]["ControlPoint"][];
        };
        CreateLocationRequest: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            name?: string | null;
        };
        PhotoPosePatch: {
            /** Format: double */
            aspect: number;
            /** Format: double */
            photo_az: number;
            /** Format: double */
            photo_tilt: number;
            /** Format: double */
            photo_roll: number;
            /** Format: double */
            size_rad: number;
            /** Format: double */
            opacity?: number;
        };
        MapMeasurementRequest: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            control_point_id?: components["schemas"]["Id"] | null;
        };
        ImageMeasurementPatch: {
            /** Format: double */
            u: number;
            /** Format: double */
            v: number;
            control_point_id?: components["schemas"]["Id"] | null;
        };
        ControlPointPatch: {
            description?: string;
            /** Format: double */
            est_lat?: number | null;
            /** Format: double */
            est_lng?: number | null;
            /** Format: double */
            est_alt?: number | null;
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        LocationId: components["schemas"]["Id"];
        PhotoId: components["schemas"]["Id"];
        MapMeasurementId: components["schemas"]["Id"];
        ImageMeasurementId: components["schemas"]["Id"];
        ControlPointId: components["schemas"]["Id"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description DB unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listLocations: {
        parameters: {
            query?: {
                /**
                 * @description Bounding box as `minLng,minLat,maxLng,maxLat` (four
                 *     comma-separated floats). When omitted, returns up to 1000
                 *     locations ordered by created_at DESC.
                 */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HydratedLocation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoPosePatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoPosePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPhotoBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadPhotoBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/*": string;
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Payload too large (above MAX_BLOB_BYTES) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createMapMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapMeasurementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMeasurement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMapMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MapMeasurementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapMeasurementRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapMeasurement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteMapMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MapMeasurementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createImageMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageMeasurementPatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMeasurement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateImageMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageMeasurementId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageMeasurementPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMeasurement"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteImageMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImageMeasurementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listControlPoints: {
        parameters: {
            query?: {
                /**
                 * @description Bounding box as `minLng,minLat,maxLng,maxLat`. Filter is
                 *     applied to the CPs' est_lat/est_lng — CPs with NULL
                 *     estimates are excluded when bbox is set. Returns up to 1000.
                 */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPointPatch"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlPointPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPoint"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteControlPoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listControlPointObservations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ControlPointId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPointObservations"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
